# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
#added a comment to make a commit

trigger:
- main

pool:
  vmImage: ubuntu-latest
  container: cypress/browsers:latest

steps:

- script: npm ci
  displayName: 'Installation'

script: npx cpypres run --browser chrome
  displayName: 'Run tests'
